version: 2
jobs:
    build:
      docker:
        - image: srcml/ubuntu_x86_64_base
      steps:
        - checkout
        - run: apt-get update
        - run: apt-get install -y git ssh
        - run: git submodule update --init --recursive
        - run: mkdir build
        - run: cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
        - run: cd build && make
        - run: ln -s build/bin bin
        - run: cd test/parser && make
